#:schema https://api.nuon.co/v1/general/config-schema?source=docker_build
name = "img_installer"
type = "docker_build"
dockerfile = "Dockerfile"

[connected_repo]
directory = "exp/installer/app"
repo      = "powertoolsdev/mono"
branch    = "ja/installer-v2"
