#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "service"
type              = "terraform_module"
terraform_version = "1.13.5"

[connected_repo]
repo      = "powertoolsdev/mono"
directory = "exp/installer/app/installer/src/service"
branch    = "ja/installer-v2"

[vars]
region                     = "{{.nuon.install_stack.outputs.region}}"
vpc_id                     = "{{.nuon.install_stack.outputs.vpc_id}}"
nuon_id                    = "{{.nuon.install.id}}"
cluster_arn                = "{{.nuon.components.cluster.outputs.cluster_arn}}"
image_url                  = "{{.nuon.components.img_installer.outputs.image.repository}}"
image_tag                  = "{{.nuon.components.img_installer.outputs.image.tag}}"
desired_count              = "{{.nuon.inputs.inputs.desired_count}}"
vendor_target_group_arn    = "{{.nuon.components.vendor_alb.outputs.target_group_arn}}"
vendor_security_group_id   = "{{.nuon.components.vendor_alb.outputs.security_group_id}}"
customer_target_group_arn  = "{{.nuon.components.customer_alb.outputs.target_group_arn}}"
customer_security_group_id = "{{.nuon.components.customer_alb.outputs.security_group_id}}"
jwt_secret                 = "{{.nuon.inputs.inputs.jwt_secret}}"
database_url               = "postgres://{{.nuon.inputs.inputs.db_username}}:{{.nuon.inputs.inputs.db_password}}@{{.nuon.components.rds.outputs.endpoint}}/{{.nuon.inputs.inputs.db_name}}?sslmode=require"
customer_base_url          = "https://{{.nuon.inputs.inputs.customer_subdomain}}.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
