---
env:
  PORT: !!string 8080
  GIN_MODE: "release"

  DB_HOST: $TFO_DB_INSTANCE_HOST
  DB_NAME: $TFO_DB_INSTANCE_NAME
  DB_USER: $TFO_DB_INSTANCE_USERNAME
  DB_PORT: !!string 5432
  DB_SSL_MODE: "verify-full"
  DB_REGION: "us-west-2"
  DB_USE_IAM: "true"

  NUON_API_URL: "https://api.nuon.co"

  CUSTOMER_BASE_URL: "https://$TFO_PUBLIC_DOMAIN"
  SUBDOMAIN_BASE_DOMAIN: "$TFO_PUBLIC_DOMAIN"
  SUPERUSER_EMAIL_DOMAIN: "nuon.co"

envSecrets:
  - name: "JWT_SECRET"
    valueFrom:
      name: customer-dashboard-jwt-secret
      key: jwt_secret
  - name: "AUTH_CLIENT_SECRET"
    valueFrom:
      name: auth-client-secret
      key: auth_client_secret
  # Other auth vars (AUTH_PROVIDER, AUTH_CLIENT_ID, etc.) are set in environment-specific templates

image:
  repository: ""
  tag: ""

namespace: "customer-dashboard"

serviceAccount:
  name: customer-dashboard
  annotations: {}

app:
  port: 8080
  liveness_probe: /livez
  readiness_probe: /readyz

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  alb:
    public_domain: $TFO_PUBLIC_DOMAIN
    public_domain_certificate: $TFO_CERTIFICATE_ARN

  autoscaling:
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
